# Generated by Django 5.2.1 on 2025-05-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
