# Generated by Django 5.2.1 on 2025-05-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otp_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.TextField(choices=[('UZS', "Uzbek so'm"), ('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('EURO', 'Euro')], default='UZS', max_length=4),
        ),
    ]
