# Generated by Django 5.2.1 on 2025-05-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='key',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
