# Generated by Django 5.2.1 on 2025-05-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
    ]
