# Generated by Django 5.2.1 on 2025-05-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='accounts/default.png', upload_to='accounts/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
