# Generated by Django 5.2.1 on 2025-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account_amount_account_description_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency_type',
            field=models.TextField(choices=[('UZS', "Uzbek so'm"), ('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('EURO', 'Euro')], default='UZS', max_length=4),
        ),
    ]
