# Generated by Django 5.2.1 on 2025-05-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_expensecategory_user_incomecategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='image',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='icon',
            field=models.CharField(choices=[('fas fa-utensils', 'Food'), ('fas fa-bus', 'Transport'), ('fas fa-heartbeat', 'Health'), ('fas fa-shopping-bag', 'Shopping'), ('fas fa-book', 'Education'), ('fas fa-film', 'Entertainment'), ('fas fa-file-invoice-dollar', 'Bills')], default='fas fa-utensils', max_length=50),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='icon',
            field=models.CharField(choices=[('fas fa-wallet', 'Salary'), ('fas fa-briefcase', 'Business'), ('fas fa-chart-line', 'Investment'), ('fas fa-gift', 'Gift'), ('fas fa-laptop-code', 'Freelance'), ('fas fa-home', 'Rental Income')], default='fas fa-wallet', max_length=50),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
