# Generated by Django 5.2.1 on 2025-05-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_expensecategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
    ]
